version: "3"
services:
  app:
    build: .
    command: node build/main.js
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BING_IMAGES_API_KEY=${BING_IMAGES_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
      - GOOGLE_CSE_API_KEY=${GOOGLE_CSE_API_KEY}
    volumes:
      - ./images:/app/images