export const HEART_TEMPLATE_PATH = '/app/templates/heart-locket.zip'
export const BELOVED_ERROR_GIF_PATH = '/app/resources/error.gif'
export const BEHATED_ERROR_GIF_PATH = '/app/resources/error_reversed.gif'
export const MAKESWEET_PATH = '/app/makesweet/reanimator'
export const IMAGE_DIRECTORY = './images'
export const IMAGE1_SUFFIX = '-image1.png'
export const IMAGE2_SUFFIX = '-image2.png'
export const GIF_EXPORT_SUFFIX = '.gif'
export const VIDEO_EXPORT_SUFFIX = '.mp4'
export const FFMPEG_EXPORT_SUFFIX = '-transcode.gif'
export const DELETE_IMAGES = true
export const STRETCH_IMAGES = true
export const TRANSCODE_FROM_MP4 = false // this option "works" but is kind of broken and will throw an error. the quality is also not better. dont wanna fix it rn
export const ONLY_USE_AVATAR_IMAGE_WHEN_NO_OTHER_TEXT = true
export const ONLY_USE_EMOTE_IMAGE_WHEN_NO_OTHER_TEXT = true
export const MAX_IMAGE_RETRY_BEFORE_CANCELLING = 10
export const BELOVED_SUFFIX = 'my beloved'
export const BEHATED_SUFFIX = 'my behated'
