export const IMAGE_DIRECTORY = './images'
export const IMAGE1_SUFFIX = '-image1.png'
export const IMAGE2_SUFFIX = '-image2.png'
export const EXPORT_SUFFIX = '.gif'
export const DELETE_IMAGES = false
export const STRETCH_IMAGES = true
export const ONLY_USE_AVATAR_IMAGE_WHEN_NO_OTHER_TEXT = true
export const ONLY_USE_EMOTE_IMAGE_WHEN_NO_OTHER_TEXT = true
export const MAX_IMAGE_RETRY_BEFORE_CANCELLING = 10
export const BELOVED_SUFFIX = 'my beloved'
export const BEHATED_SUFFIX = 'my behated'
